### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by RobinHirst11** [timrae/spotify_to_tidal#30]
just this error here ![image](https://github.com/timrae/spotify_to_tidal/assets/147210082/aaac96b1-317d-4ddf-8801-30222e4d6d43)

**Comment by timrae** [comment]
It's failing to find an artist name for that track's album. What's the spotify id for the track that's failing? If you paste the spotify id of the album that the failing track belongs to [here](https://developer.spotify.com/documentation/web-api/reference/get-an-album) and look at the json, you should be able to see why `album['artists'][0]['name']` is returning `None`

**Comment by RobinHirst11** [comment]
i made a really crude fix using the beloved and all hated GPT. i think it was a local file that i favorited so i can get it on my liked songs, (on my phone)

[sync.txt](https://github.com/timrae/spotify_to_tidal/files/15141562/sync.txt)

although its a bit... messy... and there's no end either, but it did the job!

**Comment by zackgehan** [comment]
Hi! 

I just used the project for the first time, and received the same error, for a different reason. In my case, it is because I have some playlists of podcast episodes, which ultimately send a `NoneType` object into `simple(spotify_track['album']['artists'][0]['name'])`. 

I'm not a developer at all, so I may be mistaken, but it seems like a very simple solution would be to add `if spotify_track['album']['artists'][0]['name'] is None: continue` into `get_new_spotify_tracks()`, or rather change `if not spotify_track['id']: continue` to `if not spotify_track['id'] or (spotify_track['album']['artists'][0]['name'] is None): continue`.

(To test for `show` more explicitly you'd have to search the `href`/`uri`/`external_urls` etc for the term `show` or `shows` it looks like--the `'type'` field seems to actually display the podcast channel name, not an actual type indicator.)

Of course, I'm sure there are also more advanced functionalities that could be added, like auto-skipping playlists that only contain episodes, and also handling other Spotify track types that aren't songs (if there are any--videos, audiobooks, maybe?), but this change is just one line (I think) and I'm sure those other features aren't particularly important to a lot of people. You can always put your episode playlists in the exclusions after all. 

Thank you for the tool!

**Comment by timrae** [comment]
Hi @zgcgd thanks for the report. Could you please try the code in the following PR and see if it fixes the issue?

#83

**Comment by zackgehan** [comment]
Hey, yep, works. Still creates the episode playlists, but doesn't try to copy any episodes over. (I'm not sure if spotify allows you to mix music and episodes in playlists or not, never tried.)

**Comment by timrae** [comment]
OK have released version 1.0.2 that should fix this issue also, lmk if any issues 👍

**Comment by fucksophie** [comment]
Think I'm running into a very similar issue. 
![image](https://github.com/user-attachments/assets/818e6c03-acb3-4da2-9e66-8dae3eb870e4)

**Comment by timrae** [comment]
Is it failing on a podcast or something different? Are you running the latest version?

**Comment by fucksophie** [comment]
Running the latest version, and yes it's failing on a podcast.
This one to be exact: https://open.spotify.com/episode/2bZEN988MfsVVkiWMcZqnQ?si=649a70ddad9d47d5

**Comment by timrae** [comment]
~Ah I didn't create a new release yet. You should use the latest commit on `main` instead of the release version~

**Comment by timrae** [comment]
Actually looks like I did create a release 1.0.2 with the patch, so probably the patch isn't working. I'll take a look tomorrow

**Comment by RobinHirst11** [comment]
my sollution:

dont download podcasts
![image](https://github.com/user-attachments/assets/829bce7b-a69b-4343-a670-e1b5603f0bf4)

**Comment by timrae** [comment]
Try v1.0.3

**Comment by x4xax** [comment]
Hello, I can confirm it is still failing on a podcast on latest version  : (
