### ISSUE TITLE
Add support for reverse sync

### ISSUE THREAD

**Issue by ArjonBu** [timrae/spotify_to_tidal#98]
As the title says, it would be great to support reverse sync from Tidal to Spotify too.

**Comment by timrae** [comment]
This topic has come up before, I'm certain we're syncing in the correct order, the problem is most likely that you're using different ordering settings in Tidal and Spotify. You should use sort by = 'custom order' in Spotify and click on the # in Tidal to make sure you're using the correct playlist order

**Comment by ArjonBu** [comment]
@timrae Maybe I wasn't clear but I meant support a 2 way sync
- Spotify to Tidal
- Tidal to Spotify

**Comment by timrae** [comment]
Ah ok, thanks for the additional info. It's definitely not something that I have any plans to support, but perhaps in the future it could be considered
